EAF/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # This is the home page
                       url(r'^$', views.index, name='index'),
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login', {}, name='login'),
                       url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {}, name='logout'),

                       # Profile Page
                       url(r'accounts/profile/', views.profile, name='profile'),

                       # EVE Api Proxy Endpoint
                       url(r'^api/', include('evelink.urls')),

                       # EVE Registration Endpoint
                       url(r'^eve/', include('everegister.urls', namespace="everegister")),

                       # url(r'^EAF/', include('EAF.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                        
                       # Password Reset Url's
                       url(r'^accounts/password/reset/$',
                           'django.contrib.auth.views.password_reset',
                           {'post_reset_redirect': '/accounts/password/reset/done/'},
                           name="password_reset"),

                       url(r'^accounts/password/reset/done/$',
                           'django.contrib.auth.views.password_reset_done'),

                       url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
                           'django.contrib.auth.views.password_reset_confirm',
                           {'post_reset_redirect': '/accounts/password/done/'}),

                       url(r'^accounts/password/done/$',
                           'django.contrib.auth.views.password_reset_complete'),

                       #Password Change Url's
                       url(r'^accounts/password_change/$', 
                           'django.contrib.auth.views.password_change',
                           name="password_change"),

                       url(r'^accounts/', include('django.contrib.auth.urls')),
)

#import the static urls for development
urlpatterns += staticfiles_urlpatterns()

everegister/urls.py
__author__ = 'drew'

from django.conf.urls import patterns, url
from everegister import views
from everegister.forms import EveApiForm, EveMainCharacterForm, EveRegisterForm

urlpatterns = patterns('',
                       # The registration process wizard
                       url(r'^register$', views.RegisterWizard.as_view
                           ([
                           EveApiForm,
                           EveMainCharacterForm,
                           EveRegisterForm,
                       ])
                           , name='register'),

                       #Change the API Key for the current user
                       url(r'^change_api$', views.ChangeApiWizard.as_view([
                           EveApiForm,
                           EveMainCharacterForm,
                          ]),
                          name='change_api'
                       ),

                       #Change the Main Character for the current user

                       #Display A list of known characters
                       url(r'^alliance/$', views.listAlliances, name="list_alliances"),

                       #Display information about an alliance
                       url(r'^alliance/(?P<alliance_id>\d+)/$', views.viewAlliance, name= "view_alliance"),

                       #Display A list of known characters
                       url(r'^corporation/$', views.listCorporations, name="list_corporations"),
                       #Display information about a corp
                       url(r'^corporation/(?P<corporation_id>\d+)/$', views.viewCorporation, name= "view_corporation"),

                       #Display A list of known characters
                       url(r'^character/$', views.listCharacters, name="list_characters"),

                       #Display information about a known character
                       url(r'^character/(?P<character_id>\d+)/$', views.viewCharacter, name= "view_character"),
)

EAF/views.py
from django.template import RequestContext, loader
from django.contrib.auth.decorators import login_required

__author__ = 'drew'

#Add views here

from django.http import HttpResponse


# home page with registration and login dialogs
def index(request):
    template = loader.get_template('EAF/index.html')
    context = RequestContext(request, {})
    return HttpResponse(template.render(context))

# user profile page
@login_required
def profile(request):
    template = loader.get_template('EAF/profile.html')
    context = RequestContext(request, {})
    return HttpResponse(template.render(context))

templates/EAF/index.html
{% extends "base.html" %}

{% block content_title %}
    <h1><i>Hellion Reloaded</i> News:</h1>
{% endblock %}

{% block content %}
<!-- news will go here -->
<h2>Auth Site -- <i>Aug 27th, 2013</i></h2>
<p>
The Auth site is currently in testing phase, all information will be wiped before we go to production. Much of the base infastructure is in place and the next step is rolling the plugin module for automatic registration with attached services. Thank you for your patience!
</p>
{% endblock %}

templates/EAF/profile.html
{% extends "base.html" %}

{% block content_title %}
<h1>Profile:</h1>
{% endblock %}

{% block content %}
<div class="text-left">
	<!-- basic profile stuff -->
	<label>Username:</label> <i>{{ user.username }}</i><br />
	<label>Email Address:</label> <i>{{ user.email }}</i><br />
	<label>Registration Date:</label> <i>{{ user.date_joined }}</i><br />
	<label>Account Active:</label> <i>{{ user.is_active }}</i><br />
	{% if user.evecharacter %}
	<!-- EVE Profile Information -->
	<h2><u>EVE Online:</u></h2>
	<label>Main Character:</label> <i><a href="{% url "everegister:view_character" character_id=user.evecharacter.id %}">{{ user.evecharacter.name }}</a></i><br />
	<label>Corporation:</label> <i><a href="{% url "everegister:view_corporation" corporation_id=user.evecharacter.corporation.id %}">{{ user.evecharacter.corporation.name }}</a></i><br />
	{% if user.evecharacter.alliance %}
	<label>Alliance:</label> <i><a href="{% url "everegister:view_alliance" alliance_id=user.evecharacter.alliance.id %}">{{ user.evecharacter.alliance.name }}</a></i>
	{% endif %}
	<label>API Status:</label> <i>{% if user.eveapi.valid %}Valid{% else %}Invalid (Please <a href="{% url "everegister:change_api" %}">Update</a>){% endif %}</i><br />
	<h3><u>Operations</u></h3>
	<a class="btn btn-primary" href="{% url "everegister:change_api" %}">Change Api Key</a>
	<a class="btn btn-primary">Change Main Character</a>
	{% endif %}
	<h2><u>Account Operations</u></h3>
	<a class="btn btn-warning" href="{% url "password_change" %}">Change Password</a>
</div>
{% endblock %}