EAF/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # This is the home page
                       url(r'^$', views.index, name='index'),
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login', {}, name='login'),
                       url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {}, name='logout'),

                       # Profile Page
                       url(r'accounts/profile/', views.profile, name='profile'),

                       # EVE Api Proxy Endpoint
                       url(r'^api/', include('evelink.urls')),

                       # EVE Registration Endpoint
                       url(r'^eve/', include('everegister.urls', namespace="everegister")),

                       # url(r'^EAF/', include('EAF.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                        
                       # Password Reset Url's
                       url(r'^accounts/password/reset/$',
                           'django.contrib.auth.views.password_reset',
                           {'post_reset_redirect': '/accounts/password/reset/done/'},
                           name="password_reset"),

                       url(r'^accounts/password/reset/done/$',
                           'django.contrib.auth.views.password_reset_done'),

                       url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
                           'django.contrib.auth.views.password_reset_confirm',
                           {'post_reset_redirect': '/accounts/password/done/'}),

                       url(r'^accounts/password/done/$',
                           'django.contrib.auth.views.password_reset_complete'),

                       #Password Change Url's
                       url(r'^accounts/password_change/$', 
                           'django.contrib.auth.views.password_change',
                           name="password_change"),

                       url(r'^accounts/', include('django.contrib.auth.urls')),
)

#import the static urls for development
urlpatterns += staticfiles_urlpatterns()

everegister/urls.py
__author__ = 'drew'

from django.conf.urls import patterns, url
from everegister import views
from everegister.forms import EveApiForm, EveMainCharacterForm, EveRegisterForm

urlpatterns = patterns('',
                       # The registration process wizard
                       url(r'^register$', views.RegisterWizard.as_view
                           ([
                           EveApiForm,
                           EveMainCharacterForm,
                           EveRegisterForm,
                       ])
                           , name='register'),

                       #Change the API Key for the current user
                       url(r'^change_api$', views.ChangeApiWizard.as_view([
                           EveApiForm,
                           EveMainCharacterForm,
                          ]),
                          name='change_api'
                       ),

                       #Change the Main Character for the current user

                       #Display A list of known characters
                       url(r'^alliance/$', views.listAlliances, name="list_alliances"),

                       #Display information about an alliance
                       url(r'^alliance/(?P<alliance_id>\d+)/$', views.viewAlliance, name= "view_alliance"),

                       #Display A list of known characters
                       url(r'^corporation/$', views.listCorporations, name="list_corporations"),
                       #Display information about a corp
                       url(r'^corporation/(?P<corporation_id>\d+)/$', views.viewCorporation, name= "view_corporation"),

                       #Display A list of known characters
                       url(r'^character/$', views.listCharacters, name="list_characters"),

                       #Display information about a known character
                       url(r'^character/(?P<character_id>\d+)/$', views.viewCharacter, name= "view_character"),
)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Global Scripts -->
    <!-- Bootstrap 3.0 from CDN -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="{% static "assets/css/sticky-footer-navbar.css" %}" >
    <link rel="stylesheet" href="{% static "assets/css/base.css" %}">
    {% block head %}{% endblock %}
    {% block css %}{% endblock %}
    {% block scripts %}{% endblock %}
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
  <script src="{% static "assets/js/html5shiv.js" %}"></script>
  <script src="{% static "assets/js/respond.min.js" %}"></script>
  <![endif]-->
</head>
<body id="{% block body_id %}{% endblock %}">
<div id="wrap">
{% block navbar %}
<div class="navbar navbar-inverse navbar-fixed-top active">
	<div class="navbar-inner">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Hellion Reloaded Auth</a>
			</div>
            <div class="pull-right">
                <ul class="nav navbar-nav">
					{% if user.is_authenticated %}
					    {% if user.is_staff %}
							<li><a href="{% url "admin:index" %}">Admin Portal</a></li>
						{% endif %}
						<li class="dropdown">
						    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li><a href="#">Separated link</a></li>
								<li><a href="#">One more separated link</a></li>
						  	</ul>
						</li>
						<li><a href="{% url "profile" %}">My Profile</a></li>
                        <li><a href="{% url "logout" %}">Log Out</a></li>
                    {% else %}
                        <li><a href="{% url "login" %}">Log In</a></li>
					{% endif %}
				</ul>
				{% if not user.is_authenticated %}
                	<div class="nav navbar-nav">
                		<a class="btn btn-primary" href="{% url 'everegister:register' %}">Register</a>
					</div>
				{% endif %}
			</div>
        </div>
	</div>
</div>
{% endblock %}
<div class="page-container">
    <div>
        {% block body %}
            <div>
                {% block content_title %}{% endblock %}
            </div>
            <div class="content">
                {% block content %}{% endblock %}
            </div>
        {% endblock %}
    </div>
</div>
</div>
<!-- Footer -->
<div id="footer">
	<div class="container">
	    <p class="text-muted credit">Powered By <a href="http://www.sothr.com">Sothr</a>.</p>
	</div>
</div>
<!-- Global Supplemental Scripts -->
<!-- JQuery -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- Bootstrap 3.0 from CDN -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
{% block supplementalScripts %}{% endblock %}
</body>
</html>